static struct {
        char const *module;
        char const *name;
        ValuePayload init;
        struct value value;
} builtins[] = {
#if defined(__APPLE__)
  { .module = NULL,         .name = "__apple__",                .init = BOOL_(true)                             },
  { .module = NULL,         .name = "__windows__",              .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__linux__",                .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__bsd__",                  .init = BOOL_(false)                            },
#elif defined(__linux__)
  { .module = NULL,         .name = "__apple__",                .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__windows__",              .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__linux__",                .init = BOOL_(true)                             },
  { .module = NULL,         .name = "__bsd__",                  .init = BOOL_(false)                            },
#elif defined(_WIN32)
  { .module = NULL,         .name = "__apple__",                .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__windows__",              .init = BOOL_(true)                             },
  { .module = NULL,         .name = "__linux__",                .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__bsd__",                  .init = BOOL_(false)                            },
#elif defined(__FreeBSD__)
  { .module = NULL,         .name = "__apple__",                .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__windows__",              .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__linux__",                .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__bsd__",                  .init = BOOL_(true)                             },
#else
  { .module = NULL,         .name = "__apple__",                .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__windows__",              .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__linux__",                .init = BOOL_(false)                            },
  { .module = NULL,         .name = "__bsd__",                  .init = BOOL_(false)                            },
#endif
  { .module = NULL,         .name = "print",                    .init = BUILTIN(builtin_print)                  },
  { .module = NULL,         .name = "eprint",                   .init = BUILTIN(builtin_eprint)                 },
  { .module = NULL,         .name = "slurp",                    .init = BUILTIN(builtin_slurp)                  },
  { .module = NULL,         .name = "die",                      .init = BUILTIN(builtin_die)                    },
  { .module = NULL,         .name = "__debug",                  .init = BUILTIN(builtin___debug)                },
  { .module = NULL,         .name = "doc",                      .init = BUILTIN(builtin_doc)                    },
  { .module = NULL,         .name = "setDoc",                   .init = BUILTIN(builtin_set_doc)                },
  { .module = NULL,         .name = "readLine",                 .init = BUILTIN(builtin_read)                   },
  { .module = NULL,         .name = "rand",                     .init = BUILTIN(builtin_rand)                   },
  { .module = NULL,         .name = "srand",                    .init = BUILTIN(builtin_srand)                  },
  { .module = NULL,         .name = "random",                   .init = BUILTIN(builtin_random)                 },
  { .module = NULL,         .name = "abs",                      .init = BUILTIN(builtin_abs)                    },
  { .module = NULL,         .name = "gcd",                      .init = BUILTIN(builtin_gcd)                    },
  { .module = NULL,         .name = "lcm",                      .init = BUILTIN(builtin_lcm)                    },
  { .module = NULL,         .name = "round",                    .init = BUILTIN(builtin_round)                  },
  { .module = NULL,         .name = "iround",                   .init = BUILTIN(builtin_iround)                 },
  { .module = NULL,         .name = "ceil",                     .init = BUILTIN(builtin_ceil)                   },
  { .module = NULL,         .name = "floor",                    .init = BUILTIN(builtin_floor)                  },
  { .module = NULL,         .name = "int",                      .init = BUILTIN(builtin_int)                    },
  { .module = NULL,         .name = "float",                    .init = BUILTIN(builtin_float)                  },
  { .module = NULL,         .name = "str",                      .init = BUILTIN(builtin_str)                    },
  { .module = NULL,         .name = "show",                     .init = BUILTIN(builtin_show)                   },
  { .module = NULL,         .name = "fmt",                      .init = BUILTIN(builtin_fmt)                    },
  { .module = NULL,         .name = "bool",                     .init = BUILTIN(builtin_bool)                   },
  { .module = NULL,         .name = "regex",                    .init = BUILTIN(builtin_regex)                  },
  { .module = NULL,         .name = "tuple",                    .init = BUILTIN(builtin_tuple)                  },
  { .module = NULL,         .name = "blob",                     .init = BUILTIN(builtin_blob)                   },
  { .module = NULL,         .name = "type",                     .init = BUILTIN(builtin_type)                   },
  { .module = NULL,         .name = "subclass?",                .init = BUILTIN(builtin_subclass)               },
  { .module = NULL,         .name = "members",                  .init = BUILTIN(builtin_members)                },
  { .module = NULL,         .name = "member",                   .init = BUILTIN(builtin_member)                 },
  { .module = NULL,         .name = "object",                   .init = BUILTIN(builtin_object)                 },
  { .module = NULL,         .name = "bindMethod",               .init = BUILTIN(builtin_bind)                   },
  { .module = NULL,         .name = "unbindMethod",             .init = BUILTIN(builtin_unbind)                 },
  { .module = NULL,         .name = "defineMethod",             .init = BUILTIN(builtin_define_method)          },
  { .module = NULL,         .name = "setFinalizer",             .init = BUILTIN(builtin_finalizer)              },
  { .module = NULL,         .name = "apply",                    .init = BUILTIN(builtin_apply)                  },
  { .module = NULL,         .name = "docRef",                   .init = BUILTIN(builtin_doc_ref)                },
  { .module = NULL,         .name = "ident",                    .init = BUILTIN(builtin_ident)                  },
  { .module = NULL,         .name = "min",                      .init = BUILTIN(builtin_min)                    },
  { .module = NULL,         .name = "max",                      .init = BUILTIN(builtin_max)                    },
  { .module = NULL,         .name = "chr",                      .init = BUILTIN(builtin_chr)                    },
  { .module = NULL,         .name = "ord",                      .init = BUILTIN(builtin_ord)                    },
  { .module = "ty",         .name = "hash",                     .init = BUILTIN(builtin_hash)                   },
  { .module = NULL,         .name = "md5",                      .init = BUILTIN(builtin_md5)                    },
  { .module = NULL,         .name = "sha1",                     .init = BUILTIN(builtin_sha1)                   },
  { .module = NULL,         .name = "sha256",                   .init = BUILTIN(builtin_sha256)                 },
  { .module = NULL,         .name = "sha512",                   .init = BUILTIN(builtin_sha512)                 },
  { .module = "_hash",      .name = "new",                      .init = BUILTIN(builtin_hash_new)               },
  { .module = "_hash",      .name = "update",                   .init = BUILTIN(builtin_hash_update)            },
  { .module = "_hash",      .name = "digest",                   .init = BUILTIN(builtin_hash_digest)            },
  { .module = "_hash",      .name = "copy",                     .init = BUILTIN(builtin_hash_copy)              },
  { .module = "base64",     .name = "encode",                   .init = BUILTIN(builtin_base64_encode)          },
  { .module = "base64",     .name = "decode",                   .init = BUILTIN(builtin_base64_decode)          },
  { .module = NULL,         .name = "getenv",                   .init = BUILTIN(builtin_getenv)                 },
  { .module = NULL,         .name = "setenv",                   .init = BUILTIN(builtin_setenv)                 },
  { .module = "locale",     .name = "setlocale",                .init = BUILTIN(builtin_locale_setlocale)       },
  { .module = "locale",     .name = "LC_ALL",                   .init = INT(LC_ALL)                             },
  { .module = "locale",     .name = "LC_COLLATE",               .init = INT(LC_COLLATE)                         },
  { .module = "locale",     .name = "LC_CTYPE",                 .init = INT(LC_CTYPE)                           },
  { .module = "math",       .name = "nan?",                     .init = BUILTIN(builtin_isnan)                  },
  { .module = "math",       .name = "log2",                     .init = BUILTIN(builtin_log2)                   },
  { .module = "math",       .name = "log10",                    .init = BUILTIN(builtin_log10)                  },
  { .module = "math",       .name = "log",                      .init = BUILTIN(builtin_log)                    },
  { .module = "math",       .name = "exp",                      .init = BUILTIN(builtin_exp)                    },
  { .module = "math",       .name = "pow",                      .init = BUILTIN(builtin_pow)                    },
  { .module = "math",       .name = "sinh",                     .init = BUILTIN(builtin_sinh)                   },
  { .module = "math",       .name = "cosh",                     .init = BUILTIN(builtin_cosh)                   },
  { .module = "math",       .name = "tanh",                     .init = BUILTIN(builtin_tanh)                   },
  { .module = "math",       .name = "asin",                     .init = BUILTIN(builtin_asin)                   },
  { .module = "math",       .name = "acos",                     .init = BUILTIN(builtin_acos)                   },
  { .module = "math",       .name = "atan",                     .init = BUILTIN(builtin_atan)                   },
  { .module = "math",       .name = "atan2",                    .init = BUILTIN(builtin_atan2)                  },
  { .module = "math",       .name = "sin",                      .init = BUILTIN(builtin_sin)                    },
  { .module = "math",       .name = "cos",                      .init = BUILTIN(builtin_cos)                    },
  { .module = "math",       .name = "tan",                      .init = BUILTIN(builtin_tan)                    },
  { .module = "math",       .name = "sqrt",                     .init = BUILTIN(builtin_sqrt)                   },
  { .module = "math",       .name = "cbrt",                     .init = BUILTIN(builtin_cbrt)                   },
  { .module = "math",       .name = "pi",                       .init = FLOAT(3.1415926535)                     },
  { .module = "math",       .name = "nan",                      .init = FLOAT(NAN)                              },
  { .module = "math",       .name = "inf",                      .init = FLOAT(INFINITY)                         },
  { .module = "bit",        .name = "and",                      .init = BUILTIN(builtin_bit_and)                },
  { .module = "bit",        .name = "or",                       .init = BUILTIN(builtin_bit_or)                 },
  { .module = "bit",        .name = "xor",                      .init = BUILTIN(builtin_bit_xor)                },
  { .module = "bit",        .name = "complement",               .init = BUILTIN(builtin_bit_complement)         },
  { .module = "bit",        .name = "shl",                      .init = BUILTIN(builtin_bit_shift_left)         },
  { .module = "bit",        .name = "shr",                      .init = BUILTIN(builtin_bit_shift_right)        },
#ifndef TY_WITHOUT_OS
  { .module = "os",         .name = "PATH_MAX",                 .init = INT(PATH_MAX)                           },
  { .module = "os",         .name = "NAME_MAX",                 .init = INT(NAME_MAX)                           },
  { .module = "os",         .name = "open",                     .init = BUILTIN(builtin_os_open)                },
  { .module = "os",         .name = "close",                    .init = BUILTIN(builtin_os_close)               },
  { .module = "os",         .name = "mktemp",                   .init = BUILTIN(builtin_os_mktemp)              },
  { .module = "os",         .name = "mkdtemp",                  .init = BUILTIN(builtin_os_mkdtemp)             },
  { .module = "os",         .name = "unlink",                   .init = BUILTIN(builtin_os_unlink)              },
  { .module = "os",         .name = "rename",                   .init = BUILTIN(builtin_os_rename)              },
  { .module = "os",         .name = "symlink",                  .init = BUILTIN(builtin_os_symlink)             },
  { .module = "os",         .name = "link",                     .init = BUILTIN(builtin_os_link)                },
  { .module = "os",         .name = "linkat",                   .init = BUILTIN(builtin_os_linkat)              },
  { .module = "os",         .name = "getcwd",                   .init = BUILTIN(builtin_os_getcwd)              },
  { .module = "os",         .name = "chmod",                    .init = BUILTIN(builtin_os_chmod)               },
  { .module = "os",         .name = "chown",                    .init = BUILTIN(builtin_os_chown)               },
  { .module = "os",         .name = "fchmod",                   .init = BUILTIN(builtin_os_fchmod)              },
  { .module = "os",         .name = "fchown",                   .init = BUILTIN(builtin_os_fchown)              },
  { .module = "os",         .name = "mkdir",                    .init = BUILTIN(builtin_os_mkdir)               },
  { .module = "os",         .name = "mkfifo",                   .init = BUILTIN(builtin_os_mkfifo)              },
  { .module = "os",         .name = "rmdir",                    .init = BUILTIN(builtin_os_rmdir)               },
  { .module = "os",         .name = "chdir",                    .init = BUILTIN(builtin_os_chdir)               },
  { .module = "os",         .name = "chroot",                   .init = BUILTIN(builtin_os_chroot)              },
  { .module = "os",         .name = "opendir",                  .init = BUILTIN(builtin_os_opendir)             },
  { .module = "os",         .name = "readdir",                  .init = BUILTIN(builtin_os_readdir)             },
  { .module = "os",         .name = "closedir",                 .init = BUILTIN(builtin_os_closedir)            },
  { .module = "os",         .name = "telldir",                  .init = BUILTIN(builtin_os_telldir)             },
  { .module = "os",         .name = "seekdir",                  .init = BUILTIN(builtin_os_seekdir)             },
  { .module = "os",         .name = "rewinddir",                .init = BUILTIN(builtin_os_rewinddir)           },
  { .module = "os",         .name = "read",                     .init = BUILTIN(builtin_os_read)                },
  { .module = "os",         .name = "write",                    .init = BUILTIN(builtin_os_write)               },
  { .module = "os",         .name = "pread",                    .init = BUILTIN(builtin_os_pread)               },
  { .module = "os",         .name = "pwrite",                   .init = BUILTIN(builtin_os_pwrite)              },
  { .module = "os",         .name = "sendfile",                 .init = BUILTIN(builtin_os_sendfile)            },
  { .module = "os",         .name = "splice",                   .init = BUILTIN(builtin_os_splice)              },
  { .module = "os",         .name = "copy_file_range",          .init = BUILTIN(builtin_os_copy_file_range)     },
  { .module = "os",         .name = "sync",                     .init = BUILTIN(builtin_os_sync)                },
  { .module = "os",         .name = "fsync",                    .init = BUILTIN(builtin_os_fsync)               },
  { .module = "os",         .name = "umask",                    .init = BUILTIN(builtin_os_umask)               },
  { .module = "os",         .name = "listdir",                  .init = BUILTIN(builtin_os_listdir)             },
  { .module = "os",         .name = "fcntl",                    .init = BUILTIN(builtin_os_fcntl)               },
  { .module = "os",         .name = "flock",                    .init = BUILTIN(builtin_os_flock)               },
  { .module = "os",         .name = "spawn",                    .init = BUILTIN(builtin_os_spawn)               },
  { .module = "os",         .name = "SPAWN_PIPE",               .init = INT(TY_SPAWN_PIPE)                      },
  { .module = "os",         .name = "SPAWN_NULL",               .init = INT(TY_SPAWN_NULL)                      },
  { .module = "os",         .name = "SPAWN_INHERIT",            .init = INT(TY_SPAWN_INHERIT)                   },
  { .module = "os",         .name = "SPAWN_MERGED_STDERR",      .init = INT(TY_SPAWN_MERGE_ERR)                 },
  { .module = "os",         .name = "stat",                     .init = BUILTIN(builtin_os_stat)                },
  { .module = "os",         .name = "lstat",                    .init = BUILTIN(builtin_os_lstat)               },
  { .module = "os",         .name = "fstat",                    .init = BUILTIN(builtin_os_fstat)               },
  { .module = "os",         .name = "truncate",                 .init = BUILTIN(builtin_os_truncate)            },
  { .module = "os",         .name = "ftruncate",                .init = BUILTIN(builtin_os_ftruncate)           },
  { .module = "os",         .name = "access",                   .init = BUILTIN(builtin_os_access)              },
  { .module = "os",         .name = "eaccess",                  .init = BUILTIN(builtin_os_eaccess)             },
  { .module = "os",         .name = "utimes",                   .init = BUILTIN(builtin_os_utimes)              },
  { .module = "os",         .name = "futimes",                  .init = BUILTIN(builtin_os_futimes)             },
  { .module = "os",         .name = "readlink",                 .init = BUILTIN(builtin_os_readlink)            },
  { .module = "os",         .name = "realpath",                 .init = BUILTIN(builtin_os_realpath)            },
  { .module = "os",         .name = "fork",                     .init = BUILTIN(builtin_os_fork)                },
  { .module = "os",         .name = "pipe",                     .init = BUILTIN(builtin_os_pipe)                },
#ifdef __linux__
  { .module = "os",         .name = "pipe2",                    .init = BUILTIN(builtin_os_pipe2)               },
#endif
  { .module = "os",         .name = "openpty",                  .init = BUILTIN(builtin_os_openpty)             },
  { .module = "os",         .name = "dup",                      .init = BUILTIN(builtin_os_dup)                 },
  { .module = "os",         .name = "dup2",                     .init = BUILTIN(builtin_os_dup2)                },

  { .module = "os",         .name = "mmap",                     .init = BUILTIN(builtin_os_mmap)                },
  { .module = "os",         .name = "munmap",                   .init = BUILTIN(builtin_os_munmap)              },
  { .module = "os",         .name = "mprotect",                 .init = BUILTIN(builtin_os_mprotect)            },
  { .module = "os",         .name = "PROT_READ",                .init = INT(PROT_READ)                          },
  { .module = "os",         .name = "PROT_WRITE",               .init = INT(PROT_WRITE)                         },
  { .module = "os",         .name = "PROT_EXEC",                .init = INT(PROT_EXEC)                          },
  { .module = "os",         .name = "PROT_NONE",                .init = INT(PROT_NONE)                          },
#if defined(MAP_ANON)
  { .module = "os",         .name = "MAP_ANON",                 .init = INT(MAP_ANON)                           },
#elif defined(MAP_ANONYMOUS)
  { .module = "os",         .name = "MAP_ANON",                 .init = INT(MAP_ANONYMOUS)                      },
#endif
  { .module = "os",         .name = "MAP_SHARED",               .init = INT(MAP_SHARED)                         },
  { .module = "os",         .name = "MAP_PRIVATE",              .init = INT(MAP_PRIVATE)                        },
  { .module = "os",         .name = "MAP_FIXED",                .init = INT(MAP_FIXED)                          },
  { .module = "os",         .name = "MAP_FAILED",               .init = POINTER(MAP_FAILED)                     },

#if defined(__linux__)
  { .module = "os",         .name = "AT_FDCWD",                 .init = INT(AT_FDCWD)                           },
  { .module = "os",         .name = "AT_SYMLINK_NOFOLLOW",      .init = INT(AT_SYMLINK_NOFOLLOW)                },
  { .module = "os",         .name = "AT_EMPTY_PATH",            .init = INT(AT_EMPTY_PATH)                      },
#endif

  { .module = "os",         .name = "poll",                     .init = BUILTIN(builtin_os_poll)                },
  { .module = "os",         .name = "bind",                     .init = BUILTIN(builtin_os_bind)                },
  { .module = "os",         .name = "socket",                   .init = BUILTIN(builtin_os_socket)              },
  { .module = "os",         .name = "socketpair",               .init = BUILTIN(builtin_os_socketpair)          },
  { .module = "os",         .name = "getsockopt",               .init = BUILTIN(builtin_os_getsockopt)          },
  { .module = "os",         .name = "setsockopt",               .init = BUILTIN(builtin_os_setsockopt)          },
  { .module = "os",         .name = "getpeername",              .init = BUILTIN(builtin_os_getpeername)         },
  { .module = "os",         .name = "getsockname",              .init = BUILTIN(builtin_os_getsockname)         },
  { .module = "os",         .name = "shutdown",                 .init = BUILTIN(builtin_os_shutdown)            },
  { .module = "os",         .name = "getaddrinfo",              .init = BUILTIN(builtin_os_getaddrinfo)         },
  { .module = "os",         .name = "getnameinfo",              .init = BUILTIN(builtin_os_getnameinfo)         },
  { .module = "os",         .name = "gai_strerror",             .init = BUILTIN(builtin_os_gai_strerror)        },
  { .module = "os",         .name = "accept",                   .init = BUILTIN(builtin_os_accept)              },
  { .module = "os",         .name = "listen",                   .init = BUILTIN(builtin_os_listen)              },
  { .module = "os",         .name = "SOCK_DGRAM",               .init = INT(SOCK_DGRAM)                         },
  { .module = "os",         .name = "SOCK_STREAM",              .init = INT(SOCK_STREAM)                        },
  { .module = "os",         .name = "SOCK_RAW",                 .init = INT(SOCK_RAW)                           },
  { .module = "os",         .name = "AF_INET",                  .init = INT(AF_INET)                            },
  { .module = "os",         .name = "AF_INET6",                 .init = INT(AF_INET6)                           },
  { .module = "os",         .name = "AF_UNIX",                  .init = INT(AF_UNIX)                            },
  { .module = "os",         .name = "AF_UNSPEC",                .init = INT(AF_UNSPEC)                          },
  { .module = "os",         .name = "AI_PASSIVE",               .init = INT(AI_PASSIVE)                         },
  { .module = "os",         .name = "AI_ALL",                   .init = INT(AI_ALL)                             },
  { .module = "os",         .name = "AI_CANONNAME",             .init = INT(AI_CANONNAME)                       },
  { .module = "os",         .name = "AI_ADDRCONFIG",            .init = INT(AI_ADDRCONFIG)                      },
  { .module = "os",         .name = "AI_V4MAPPED",              .init = INT(AI_V4MAPPED)                        },
  { .module = "os",         .name = "NI_NAMEREQD",              .init = INT(NI_NAMEREQD)                        },
  { .module = "os",         .name = "NI_DGRAM",                 .init = INT(NI_DGRAM)                           },
  { .module = "os",         .name = "NI_NOFQDN",                .init = INT(NI_NOFQDN)                          },
  { .module = "os",         .name = "NI_NUMERICHOST",           .init = INT(NI_NUMERICHOST)                     },
  { .module = "os",         .name = "NI_NUMERICSERV",           .init = INT(NI_NUMERICSERV)                     },
  { .module = "os",         .name = "SOL_SOCKET",               .init = INT(SOL_SOCKET)                         },
  { .module = "os",         .name = "SO_REUSEADDR",             .init = INT(SO_REUSEADDR)                       },
  { .module = "os",         .name = "SO_LINGER",                .init = INT(SO_LINGER)                          },
  { .module = "os",         .name = "SHUT_RD",                  .init = INT(SHUT_RD)                            },
  { .module = "os",         .name = "SHUT_WR",                  .init = INT(SHUT_WR)                            },
  { .module = "os",         .name = "SHUT_RDWR",                .init = INT(SHUT_RDWR)                          },
  { .module = "os",         .name = "kill",                     .init = BUILTIN(builtin_os_kill)                },
  { .module = "os",         .name = "raise",                    .init = BUILTIN(builtin_os_raise)               },
  { .module = "os",         .name = "signal",                   .init = BUILTIN(builtin_os_signal)              },

  { .module = "os",         .name = "SIG_DFL",                  .init = INT(0)                                  },
  { .module = "os",         .name = "SIG_IGN",                  .init = INT(1)                                  },

  { .module = "os",         .name = "signame",                  .init = BUILTIN(builtin_os_signame)             },
  { .module = "os",         .name = "strsignal",                .init = BUILTIN(builtin_os_strsignal)           },

  { .module = "os",         .name = "sigprocmask",              .init = BUILTIN(builtin_os_sigprocmask)         },
  { .module = "os",         .name = "sigpending",               .init = BUILTIN(builtin_os_sigpending)          },
  { .module = "os",         .name = "sigsuspend",               .init = BUILTIN(builtin_os_sigsuspend)          },
  { .module = "os",         .name = "sigwaitinfo",              .init = BUILTIN(builtin_os_sigwaitinfo)         },
  { .module = "os",         .name = "sigwait",                  .init = BUILTIN(builtin_os_sigwait)             },
  { .module = "os",         .name = "SIG_BLOCK",                .init = INT(SIG_BLOCK)                          },
  { .module = "os",         .name = "SIG_UNBLOCK",              .init = INT(SIG_UNBLOCK)                        },
  { .module = "os",         .name = "SIG_SETMASK",              .init = INT(SIG_SETMASK)                        },

  { .module = "os",         .name = "sigset",                   .init = BUILTIN(builtin_os_sigset)              },
  { .module = "os",         .name = "sigemptyset",              .init = BUILTIN(builtin_os_sigemptyset)         },
  { .module = "os",         .name = "sigfillset",               .init = BUILTIN(builtin_os_sigfillset)          },
  { .module = "os",         .name = "sigaddset",                .init = BUILTIN(builtin_os_sigaddset)           },
  { .module = "os",         .name = "sigdelset",                .init = BUILTIN(builtin_os_sigdelset)           },
  { .module = "os",         .name = "sigismember",              .init = BUILTIN(builtin_os_sigismember)         },

  { .module = "os",         .name = "exit",                     .init = BUILTIN(builtin_os_exit)                },
  { .module = "os",         .name = "pause",                    .init = BUILTIN(builtin_os_pause)               },
  { .module = "os",         .name = "isatty",                   .init = BUILTIN(builtin_os_isatty)              },
  { .module = "os",         .name = "ttyname",                  .init = BUILTIN(builtin_os_ttyname)             },
  { .module = "os",         .name = "terminalSize",             .init = BUILTIN(builtin_os_terminal_size)       },
  { .module = "os",         .name = "ncpu",                     .init = BUILTIN(builtin_os_cpu_count)           },
  { .module = "os",         .name = "exec",                     .init = BUILTIN(builtin_os_exec)                },
  { .module = "os",         .name = "getpid",                   .init = BUILTIN(builtin_os_getpid)              },
  { .module = "os",         .name = "getppid",                  .init = BUILTIN(builtin_os_getppid)             },
  { .module = "os",         .name = "getpgid",                  .init = BUILTIN(builtin_os_getpgid)             },
  { .module = "os",         .name = "setpgid",                  .init = BUILTIN(builtin_os_setpgid)             },
  { .module = "os",         .name = "getuid",                   .init = BUILTIN(builtin_os_getuid)              },
  { .module = "os",         .name = "geteuid",                  .init = BUILTIN(builtin_os_geteuid)             },
  { .module = "os",         .name = "getgid",                   .init = BUILTIN(builtin_os_getgid)              },
  { .module = "os",         .name = "getegid",                  .init = BUILTIN(builtin_os_getegid)             },
  { .module = "os",         .name = "setuid",                   .init = BUILTIN(builtin_os_setuid)              },
  { .module = "os",         .name = "seteuid",                  .init = BUILTIN(builtin_os_seteuid)             },
  { .module = "os",         .name = "setgid",                   .init = BUILTIN(builtin_os_setgid)              },
  { .module = "os",         .name = "setegid",                  .init = BUILTIN(builtin_os_setegid)             },
  { .module = "os",         .name = "getsid",                   .init = BUILTIN(builtin_os_getsid)              },
  { .module = "os",         .name = "setsid",                   .init = BUILTIN(builtin_os_setsid)              },
  { .module = "os",         .name = "wait",                     .init = BUILTIN(builtin_os_wait)                },
  { .module = "os",         .name = "wait4",                    .init = BUILTIN(builtin_os_wait4)               },
  { .module = "os",         .name = "WIFSTOPPED",               .init = BUILTIN(builtin_os_WIFSTOPPED)          },
  { .module = "os",         .name = "WIFEXITED",                .init = BUILTIN(builtin_os_WIFEXITED)           },
  { .module = "os",         .name = "WEXITSTATUS",              .init = BUILTIN(builtin_os_WEXITSTATUS)         },
  { .module = "os",         .name = "WIFSIGNALED",              .init = BUILTIN(builtin_os_WIFSIGNALED)         },
  { .module = "os",         .name = "WTERMSIG",                 .init = BUILTIN(builtin_os_WTERMSIG)            },
  { .module = "os",         .name = "WSTOPSIG",                 .init = BUILTIN(builtin_os_WSTOPSIG)            },
#ifdef WCOREDUMP
  { .module = "os",         .name = "WCOREDUMP",                .init = BUILTIN(builtin_os_WCOREDUMP)           },
#endif
#ifdef WIFCONTINUED
  { .module = "os",         .name = "WIFCONTINUED",             .init = BUILTIN(builtin_os_WIFCONTINUED)        },
#endif
#ifdef __linux__
  { .module = "os",         .name = "epoll_create",             .init = BUILTIN(builtin_os_epoll_create)        },
  { .module = "os",         .name = "epoll_ctl",                .init = BUILTIN(builtin_os_epoll_ctl)           },
  { .module = "os",         .name = "epoll_wait",               .init = BUILTIN(builtin_os_epoll_wait)          },
  { .module = "os",         .name = "EPOLL_CTL_ADD",            .init = INT(EPOLL_CTL_ADD)                      },
  { .module = "os",         .name = "EPOLL_CTL_DEL",            .init = INT(EPOLL_CTL_DEL)                      },
  { .module = "os",         .name = "EPOLL_CTL_MOD",            .init = INT(EPOLL_CTL_MOD)                      },
  { .module = "os",         .name = "EPOLLIN",                  .init = INT(EPOLLIN)                            },
  { .module = "os",         .name = "EPOLLET",                  .init = INT(EPOLLET)                            },
  { .module = "os",         .name = "EPOLLOUT",                 .init = INT(EPOLLOUT)                           },
  { .module = "os",         .name = "EPOLLHUP",                 .init = INT(EPOLLHUP)                           },

  { .module = "os",         .name = "eventfd",                  .init = BUILTIN(builtin_os_eventfd)             },
  { .module = "os",         .name = "EFD_CLOEXEC",              .init = INT(EFD_CLOEXEC)                        },
  { .module = "os",         .name = "EFD_NONBLOCK",             .init = INT(EFD_NONBLOCK)                       },
  { .module = "os",         .name = "EFD_SEMAPHORE",            .init = INT(EFD_SEMAPHORE)                      },

  { .module = "os",         .name = "inotify_init",             .init = BUILTIN(builtin_os_inotify_init)        },
  { .module = "os",         .name = "inotify_add_watch",        .init = BUILTIN(builtin_os_inotify_add_watch)   },
  { .module = "os",         .name = "inotify_rm_watch",         .init = BUILTIN(builtin_os_inotify_rm_watch)    },
  { .module = "os",         .name = "IN_ACCESS",                .init = INT(IN_ACCESS)                          },
  { .module = "os",         .name = "IN_MODIFY",                .init = INT(IN_MODIFY)                          },
  { .module = "os",         .name = "IN_ATTRIB",                .init = INT(IN_ATTRIB)                          },
  { .module = "os",         .name = "IN_CLOSE_WRITE",           .init = INT(IN_CLOSE_WRITE)                     },
  { .module = "os",         .name = "IN_CLOSE_NOWRITE",         .init = INT(IN_CLOSE_NOWRITE)                   },
  { .module = "os",         .name = "IN_OPEN",                  .init = INT(IN_OPEN)                            },
  { .module = "os",         .name = "IN_MOVED_FROM",            .init = INT(IN_MOVED_FROM)                      },
  { .module = "os",         .name = "IN_MOVED_TO",              .init = INT(IN_MOVED_TO)                        },
  { .module = "os",         .name = "IN_CREATE",                .init = INT(IN_CREATE)                          },
  { .module = "os",         .name = "IN_DELETE",                .init = INT(IN_DELETE)                          },
  { .module = "os",         .name = "IN_DELETE_SELF",           .init = INT(IN_DELETE_SELF)                     },
  { .module = "os",         .name = "IN_MOVE_SELF",             .init = INT(IN_MOVE_SELF)                       },
  { .module = "os",         .name = "IN_ALL_EVENTS",            .init = INT(IN_ALL_EVENTS)                      },
  { .module = "os",         .name = "IN_NONBLOCK",              .init = INT(IN_NONBLOCK)                        },
  { .module = "os",         .name = "IN_CLOEXEC",               .init = INT(IN_CLOEXEC)                         },

  { .module = "os",         .name = "signalfd",                 .init = BUILTIN(builtin_os_signalfd)            },
  { .module = "os",         .name = "SFD_CLOEXEC",              .init = INT(SFD_CLOEXEC)                        },
  { .module = "os",         .name = "SFD_NONBLOCK",             .init = INT(SFD_NONBLOCK)                       },

  { .module = "os",         .name = "timerfd_create",           .init = BUILTIN(builtin_os_timerfd_create)      },
  { .module = "os",         .name = "timerfd_settime",          .init = BUILTIN(builtin_os_timerfd_settime)     },
  { .module = "os",         .name = "timerfd_gettime",          .init = BUILTIN(builtin_os_timerfd_gettime)     },
  { .module = "os",         .name = "TFD_CLOEXEC",              .init = INT(TFD_CLOEXEC)                        },
  { .module = "os",         .name = "TFD_NONBLOCK",             .init = INT(TFD_NONBLOCK)                       },
  { .module = "os",         .name = "TFD_TIMER_ABSTIME",        .init = INT(TFD_TIMER_ABSTIME)                  },
#endif

  { .module = "os",         .name = "recvfrom",                 .init = BUILTIN(builtin_os_recvfrom)            },
  { .module = "os",         .name = "sendto",                   .init = BUILTIN(builtin_os_sendto)              },
  { .module = "os",         .name = "connect",                  .init = BUILTIN(builtin_os_connect)             },
  { .module = "os",         .name = "usleep",                   .init = BUILTIN(builtin_os_usleep)              },
  { .module = "os",         .name = "sleep",                    .init = BUILTIN(builtin_os_sleep)               },
  { .module = "os",         .name = "POLLIN",                   .init = INT(POLLIN)                             },
  { .module = "os",         .name = "POLLOUT",                  .init = INT(POLLOUT)                            },
  { .module = "os",         .name = "POLLHUP",                  .init = INT(POLLHUP)                            },
  { .module = "os",         .name = "POLLERR",                  .init = INT(POLLERR)                            },
  { .module = "os",         .name = "POLLNVAL",                 .init = INT(POLLNVAL)                           },
  { .module = "os",         .name = "O_ACCMODE",                .init = INT(O_ACCMODE)                          },
  { .module = "os",         .name = "O_RDWR",                   .init = INT(O_RDWR)                             },
  { .module = "os",         .name = "O_CREAT",                  .init = INT(O_CREAT)                            },
  { .module = "os",         .name = "O_RDONLY",                 .init = INT(O_RDONLY)                           },
  { .module = "os",         .name = "O_WRONLY",                 .init = INT(O_WRONLY)                           },
  { .module = "os",         .name = "O_TRUNC",                  .init = INT(O_TRUNC)                            },
  { .module = "os",         .name = "O_APPEND",                 .init = INT(O_APPEND)                           },
  { .module = "os",         .name = "O_NONBLOCK",               .init = INT(O_NONBLOCK)                         },
  { .module = "os",         .name = "O_ASYNC",                  .init = INT(O_ASYNC)                            },
  { .module = "os",         .name = "O_DIRECTORY",              .init = INT(O_DIRECTORY)                        },
  { .module = "os",         .name = "O_EXCL",                   .init = INT(O_EXCL)                             },
  { .module = "os",         .name = "O_NOFOLLOW",               .init = INT(O_NOFOLLOW)                         },
  { .module = "os",         .name = "O_CLOEXEC",                .init = INT(O_CLOEXEC)                          },
#ifdef O_NOCTTY
  { .module = "os",         .name = "O_NOCTTY",                 .init = INT(O_NOCTTY)                           },
#endif
#ifdef O_DSYNC
  { .module = "os",         .name = "O_DSYNC",                  .init = INT(O_DSYNC)                            },
#endif
#ifdef O_RSYNC
  { .module = "os",         .name = "O_RSYNC",                  .init = INT(O_RSYNC)                            },
#endif
#ifdef O_SYNC
  { .module = "os",         .name = "O_SYNC",                   .init = INT(O_SYNC)                             },
#endif
#ifdef O_TMPFILE
  { .module = "os",         .name = "O_TMPFILE",                .init = INT(O_TMPFILE)                          },
#endif

#if defined(__APPLE__) || defined(__linux__)
  { .module = "os",         .name = "AT_FDCWD",                 .init = INT(AT_FDCWD)                          },
  { .module = "os",         .name = "AT_EACCESS",               .init = INT(AT_EACCESS)                        },
  { .module = "os",         .name = "AT_REMOVEDIR",             .init = INT(AT_REMOVEDIR)                      },
  { .module = "os",         .name = "AT_SYMLINK_FOLLOW",        .init = INT(AT_SYMLINK_FOLLOW)                 },
  { .module = "os",         .name = "AT_SYMLINK_NOFOLLOW",      .init = INT(AT_SYMLINK_NOFOLLOW)               },
#endif

#if defined(__linux__)
  { .module = "os",         .name = "AT_STATX_SYNC_AS_STAT",    .init = INT(AT_STATX_SYNC_AS_STAT)             },
  { .module = "os",         .name = "AT_STATX_FORCE_SYNC",      .init = INT(AT_STATX_FORCE_SYNC)               },
  { .module = "os",         .name = "AT_STATX_DONT_SYNC",       .init = INT(AT_STATX_DONT_SYNC)                },
  { .module = "os",         .name = "AT_RECURSIVE",             .init = INT(AT_RECURSIVE)                      },
  { .module = "os",         .name = "AT_EMPTY_PATH",            .init = INT(AT_EMPTY_PATH)                     },
  { .module = "os",         .name = "AT_NO_AUTOMOUNT",          .init = INT(AT_NO_AUTOMOUNT)                   },
#endif

#ifdef WNOHANG
  { .module = "os",         .name = "WNOHANG",                  .init = INT(WNOHANG)                            },
#endif
#ifdef WUNTRACED
  { .module = "os",         .name = "WUNTRACED",                .init = INT(WUNTRACED)                          },
#endif
#ifdef WCONTINUED
  { .module = "os",         .name = "WCONTINUED",               .init = INT(WCONTINUED)                         },
#endif
#ifndef _WIN32
  { .module = "os",         .name = "F_SETFD",                  .init = INT(F_SETFD)                            },
  { .module = "os",         .name = "F_GETFD",                  .init = INT(F_GETFD)                            },
  { .module = "os",         .name = "F_GETFL",                  .init = INT(F_GETFL)                            },
  { .module = "os",         .name = "F_SETFL",                  .init = INT(F_SETFL)                            },
  { .module = "os",         .name = "F_DUPFD",                  .init = INT(F_DUPFD)                            },
  { .module = "os",         .name = "F_SETOWN",                 .init = INT(F_SETOWN)                           },
  { .module = "os",         .name = "F_GETOWN",                 .init = INT(F_GETOWN)                           },
#if defined(F_GETPATH) && defined(F_SETNOSIGPIPE)
  { .module = "os",         .name = "F_DUPFD_CLOEXEC",          .init = INT(F_DUPFD_CLOEXEC)                    },
  { .module = "os",         .name = "F_GETPATH",                .init = INT(F_GETPATH)                          },
  { .module = "os",         .name = "F_PREALLOCATE",            .init = INT(F_PREALLOCATE)                      },
  { .module = "os",         .name = "F_SETSIZE",                .init = INT(F_SETSIZE)                          },
  { .module = "os",         .name = "F_RDADVISE",               .init = INT(F_RDADVISE)                         },
  { .module = "os",         .name = "F_RDAHEAD",                .init = INT(F_RDAHEAD)                          },
  { .module = "os",         .name = "F_NOCACHE",                .init = INT(F_NOCACHE)                          },
  { .module = "os",         .name = "F_LOG2PHYS",               .init = INT(F_LOG2PHYS)                         },
  { .module = "os",         .name = "F_LOG2PHYS_EXT",           .init = INT(F_LOG2PHYS_EXT)                     },
  { .module = "os",         .name = "F_FULLFSYNC",              .init = INT(F_FULLFSYNC)                        },
  { .module = "os",         .name = "F_SETNOSIGPIPE",           .init = INT(F_SETNOSIGPIPE)                     },
  { .module = "os",         .name = "F_GETNOSIGPIPE",           .init = INT(F_GETNOSIGPIPE)                     },
#endif
#if defined(F_GETSIG) && defined(F_SETSIG)
  { .module = "os",         .name = "F_GETSIG",                 .init = INT(F_GETSIG)                           },
  { .module = "os",         .name = "F_SETSIG",                 .init = INT(F_SETSIG)                           },
#endif
#endif
#endif

#ifdef _WIN32
     #define   LOCK_SH   1    /* shared lock */
     #define   LOCK_EX   2    /* exclusive lock */
     #define   LOCK_NB   4    /* don't block when locking */
     #define   LOCK_UN   8    /* unlock */
#endif

  { .module = "os",         .name = "R_OK",                     .init = INT(R_OK)                              },
  { .module = "os",         .name = "W_OK",                     .init = INT(W_OK)                              },
  { .module = "os",         .name = "X_OK",                     .init = INT(X_OK)                              },
  { .module = "os",         .name = "F_OK",                     .init = INT(F_OK)                              },

  { .module = "os",         .name = "LOCK_SH",                  .init = INT(LOCK_SH)                            },
  { .module = "os",         .name = "LOCK_EX",                  .init = INT(LOCK_EX)                            },
  { .module = "os",         .name = "LOCK_NB",                  .init = INT(LOCK_NB)                            },
  { .module = "os",         .name = "LOCK_UN",                  .init = INT(LOCK_UN)                            },

  { .module = "os",         .name = "lseek",                    .init = BUILTIN(builtin_os_lseek)               },
  { .module = "os",         .name = "SEEK_SET",                 .init = INT(SEEK_SET)                           },
  { .module = "os",         .name = "SEEK_CUR",                 .init = INT(SEEK_CUR)                           },
  { .module = "os",         .name = "SEEK_END",                 .init = INT(SEEK_END)                           },
  { .module = "os",         .name = "SEEK_DATA",                .init = INT(SEEK_DATA)                          },
  { .module = "os",         .name = "SEEK_HOLE",                .init = INT(SEEK_HOLE)                          },

#if defined(__linux__)
  { .module = "os",         .name = "CLONE_CHILD_CLEARTID",     .init = INT(CLONE_CHILD_CLEARTID)               },
  { .module = "os",         .name = "CLONE_CHILD_SETTID",       .init = INT(CLONE_CHILD_SETTID)                 },
  { .module = "os",         .name = "CLONE_DETACHED",           .init = INT(CLONE_DETACHED)                     },
  { .module = "os",         .name = "CLONE_FILES",              .init = INT(CLONE_FILES)                        },
  { .module = "os",         .name = "CLONE_FS",                 .init = INT(CLONE_FS)                           },
  { .module = "os",         .name = "CLONE_IO",                 .init = INT(CLONE_IO)                           },
  { .module = "os",         .name = "CLONE_NEWCGROUP",          .init = INT(CLONE_NEWCGROUP)                    },
  { .module = "os",         .name = "CLONE_NEWIPC",             .init = INT(CLONE_NEWIPC)                       },
  { .module = "os",         .name = "CLONE_NEWNET",             .init = INT(CLONE_NEWNET)                       },
  { .module = "os",         .name = "CLONE_NEWNS",              .init = INT(CLONE_NEWNS)                        },
  { .module = "os",         .name = "CLONE_NEWPID",             .init = INT(CLONE_NEWPID)                       },
  { .module = "os",         .name = "CLONE_NEWUSER",            .init = INT(CLONE_NEWUSER)                      },
  { .module = "os",         .name = "CLONE_NEWUTS",             .init = INT(CLONE_NEWUTS)                       },
  { .module = "os",         .name = "CLONE_PARENT_SETTID",      .init = INT(CLONE_PARENT_SETTID)                },
  { .module = "os",         .name = "CLONE_PARENT",             .init = INT(CLONE_PARENT)                       },
  { .module = "os",         .name = "CLONE_PTRACE",             .init = INT(CLONE_PTRACE)                       },
  { .module = "os",         .name = "CLONE_SETTLS",             .init = INT(CLONE_SETTLS)                       },
  { .module = "os",         .name = "CLONE_SIGHAND",            .init = INT(CLONE_SIGHAND)                      },
  { .module = "os",         .name = "CLONE_SYSVSEM",            .init = INT(CLONE_SYSVSEM)                      },
  { .module = "os",         .name = "CLONE_THREAD",             .init = INT(CLONE_THREAD)                       },
  { .module = "os",         .name = "CLONE_UNTRACED",           .init = INT(CLONE_UNTRACED)                     },
  { .module = "os",         .name = "CLONE_VFORK",              .init = INT(CLONE_VFORK)                        },
  { .module = "os",         .name = "CLONE_VM",                 .init = INT(CLONE_VM)                           },

  { .module = "os",         .name = "MNT_DETACH",               .init = INT(MNT_DETACH)                         },
  { .module = "os",         .name = "MNT_EXPIRE",               .init = INT(MNT_EXPIRE)                         },
  { .module = "os",         .name = "MNT_FORCE",                .init = INT(MNT_FORCE)                          },

  { .module = "os",         .name = "MS_BIND",                  .init = INT(MS_BIND)                            },
  { .module = "os",         .name = "MS_DIRSYNC",               .init = INT(MS_DIRSYNC)                         },
  { .module = "os",         .name = "MS_INVALIDATE",            .init = INT(MS_INVALIDATE)                      },
  { .module = "os",         .name = "MS_MANDLOCK",              .init = INT(MS_MANDLOCK)                        },
  { .module = "os",         .name = "MS_MOVE",                  .init = INT(MS_MOVE)                            },
  { .module = "os",         .name = "MS_NOATIME",               .init = INT(MS_NOATIME)                         },
  { .module = "os",         .name = "MS_NODEV",                 .init = INT(MS_NODEV)                           },
  { .module = "os",         .name = "MS_NODIRATIME",            .init = INT(MS_NODIRATIME)                      },
  { .module = "os",         .name = "MS_NOEXEC",                .init = INT(MS_NOEXEC)                          },
  { .module = "os",         .name = "MS_NOSUID",                .init = INT(MS_NOSUID)                          },
  { .module = "os",         .name = "MS_PRIVATE",               .init = INT(MS_PRIVATE)                         },
  { .module = "os",         .name = "MS_RDONLY",                .init = INT(MS_RDONLY)                          },
  { .module = "os",         .name = "MS_REC",                   .init = INT(MS_REC)                             },
  { .module = "os",         .name = "MS_RELATIME",              .init = INT(MS_RELATIME)                        },
  { .module = "os",         .name = "MS_REMOUNT",               .init = INT(MS_REMOUNT)                         },
  { .module = "os",         .name = "MS_SHARED",                .init = INT(MS_SHARED)                          },
  { .module = "os",         .name = "MS_SILENT",                .init = INT(MS_SILENT)                          },
  { .module = "os",         .name = "MS_SLAVE",                 .init = INT(MS_SLAVE)                           },
  { .module = "os",         .name = "MS_STRICTATIME",           .init = INT(MS_STRICTATIME)                     },
  { .module = "os",         .name = "MS_SYNCHRONOUS",           .init = INT(MS_SYNCHRONOUS)                     },
  { .module = "os",         .name = "MS_UNBINDABLE",            .init = INT(MS_UNBINDABLE)                      },
#endif

  { .module = "thread",     .name = "create",                   .init = BUILTIN(builtin_thread_create)           },
  { .module = "thread",     .name = "join",                     .init = BUILTIN(builtin_thread_join)             },
  { .module = "thread",     .name = "detach",                   .init = BUILTIN(builtin_thread_detach)           },
  { .module = "thread",     .name = "kill",                     .init = BUILTIN(builtin_thread_kill)             },
  { .module = "thread",     .name = "mutex",                    .init = BUILTIN(builtin_thread_mutex)            },
  { .module = "thread",     .name = "spinLock",                 .init = BUILTIN(builtin_thread_spinlock)         },
  { .module = "thread",     .name = "lock",                     .init = BUILTIN(builtin_thread_lock)             },
  { .module = "thread",     .name = "unlock",                   .init = BUILTIN(builtin_thread_unlock)           },
  { .module = "thread",     .name = "tryLock",                  .init = BUILTIN(builtin_thread_trylock)          },
  { .module = "thread",     .name = "cond",                     .init = BUILTIN(builtin_thread_cond)             },
  { .module = "thread",     .name = "waitCond",                 .init = BUILTIN(builtin_thread_cond_wait)        },
  { .module = "thread",     .name = "signalCond",               .init = BUILTIN(builtin_thread_cond_signal)      },
  { .module = "thread",     .name = "broadcastCond",            .init = BUILTIN(builtin_thread_cond_broadcast)   },
  { .module = "thread",     .name = "setName",                  .init = BUILTIN(builtin_thread_setname)          },
  { .module = "thread",     .name = "getName",                  .init = BUILTIN(builtin_thread_getname)          },
  { .module = "thread",     .name = "self",                     .init = BUILTIN(builtin_thread_self)             },
  { .module = "thread",     .name = "group",                    .init = BUILTIN(builtin_thread_group)            },
  { .module = "thread",     .name = "id",                       .init = BUILTIN(builtin_thread_id)               },
  { .module = "thread",     .name = "channel",                  .init = BUILTIN(builtin_thread_channel)          },
  { .module = "thread",     .name = "close",                    .init = BUILTIN(builtin_thread_close)            },
  { .module = "thread",     .name = "send",                     .init = BUILTIN(builtin_thread_send)             },
  { .module = "thread",     .name = "recv",                     .init = BUILTIN(builtin_thread_recv)             },
  { .module = "thread",     .name = "sigmask",                  .init = BUILTIN(builtin_thread_sigmask)          },
  { .module = "thread",     .name = "note",                     .init = BUILTIN(builtin_thread_note)             },
  { .module = "thread",     .name = "notify",                   .init = BUILTIN(builtin_thread_notify)           },
  { .module = "thread",     .name = "notified?",                .init = BUILTIN(builtin_thread_is_notified)      },
  { .module = "thread",     .name = "waitNote",                 .init = BUILTIN(builtin_thread_wait_note)        },
  { .module = "thread",     .name = "counter",                  .init = BUILTIN(builtin_thread_counter)          },
  { .module = "thread",     .name = "countAdd",                 .init = BUILTIN(builtin_thread_count_add)        },
  { .module = "thread",     .name = "countValue",               .init = BUILTIN(builtin_thread_count_value)      },
  { .module = "thread",     .name = "countWait",                .init = BUILTIN(builtin_thread_count_wait)       },
  { .module = "thread",     .name = "waitAny",                  .init = BUILTIN(builtin_thread_wait_any)         },
  { .module = "thread",     .name = "atomic",                   .init = BUILTIN(builtin_thread_atomic)           },
  { .module = "thread",     .name = "load",                     .init = BUILTIN(builtin_thread_atomic_load)      },
  { .module = "thread",     .name = "store",                    .init = BUILTIN(builtin_thread_atomic_store)     },
  { .module = "thread",     .name = "swap",                     .init = BUILTIN(builtin_thread_atomic_swap)      },
  { .module = "thread",     .name = "trySwap",                  .init = BUILTIN(builtin_thread_atomic_cmpxchg)   },
  { .module = "thread",     .name = "fetchAdd",                 .init = BUILTIN(builtin_thread_atomic_fetch_add) },
  { .module = "thread",     .name = "fetchSub",                 .init = BUILTIN(builtin_thread_atomic_fetch_sub) },

  { .module = "stdio",      .name = "fdopen",                   .init = BUILTIN(builtin_stdio_fdopen)           },
  { .module = "stdio",      .name = "fileno",                   .init = BUILTIN(builtin_stdio_fileno)           },
  { .module = "stdio",      .name = "tmpfile",                  .init = BUILTIN(builtin_stdio_tmpfile)          },
  { .module = "stdio",      .name = "fgets",                    .init = BUILTIN(builtin_stdio_fgets)            },
  { .module = "stdio",      .name = "fread",                    .init = BUILTIN(builtin_stdio_fread)            },
  { .module = "stdio",      .name = "readSigned",               .init = BUILTIN(builtin_stdio_read_signed)      },
  { .module = "stdio",      .name = "readUnsigned",             .init = BUILTIN(builtin_stdio_read_unsigned)    },
  { .module = "stdio",      .name = "readFloat",                .init = BUILTIN(builtin_stdio_read_float)       },
  { .module = "stdio",      .name = "readDouble",               .init = BUILTIN(builtin_stdio_read_double)      },
  { .module = "stdio",      .name = "writeFloat",               .init = BUILTIN(builtin_stdio_write_float)      },
  { .module = "stdio",      .name = "writeDouble",              .init = BUILTIN(builtin_stdio_write_double)     },
  { .module = "stdio",      .name = "writeSigned",              .init = BUILTIN(builtin_stdio_write_signed)     },
  { .module = "stdio",      .name = "writeUnsigned",            .init = BUILTIN(builtin_stdio_write_unsigned)   },
  { .module = "stdio",      .name = "slurp",                    .init = BUILTIN(builtin_stdio_slurp)            },
  { .module = "stdio",      .name = "puts",                     .init = BUILTIN(builtin_stdio_puts)             },
  { .module = "stdio",      .name = "fwrite",                   .init = BUILTIN(builtin_stdio_fwrite)           },
  { .module = "stdio",      .name = "fgetc",                    .init = BUILTIN(builtin_stdio_fgetc)            },
  { .module = "stdio",      .name = "fputc",                    .init = BUILTIN(builtin_stdio_fputc)            },
  { .module = "stdio",      .name = "fflush",                   .init = BUILTIN(builtin_stdio_fflush)           },
  { .module = "stdio",      .name = "fclose",                   .init = BUILTIN(builtin_stdio_fclose)           },
  { .module = "stdio",      .name = "clearerr",                 .init = BUILTIN(builtin_stdio_clearerr)         },
  { .module = "stdio",      .name = "fseek",                    .init = BUILTIN(builtin_stdio_fseek)            },
  { .module = "stdio",      .name = "ftell",                    .init = BUILTIN(builtin_stdio_ftell)            },
  { .module = "stdio",      .name = "setvbuf",                  .init = BUILTIN(builtin_stdio_setvbuf)          },
  { .module = "stdio",      .name = "_IOLBF",                   .init = INT(_IOLBF)                             },
  { .module = "stdio",      .name = "_IOFBF",                   .init = INT(_IOFBF)                             },
  { .module = "stdio",      .name = "_IONBF",                   .init = INT(_IONBF)                             },
  { .module = "stdio",      .name = "SEEK_SET",                 .init = INT(SEEK_SET)                           },
  { .module = "stdio",      .name = "SEEK_CUR",                 .init = INT(SEEK_CUR)                           },
  { .module = "stdio",      .name = "SEEK_END",                 .init = INT(SEEK_END)                           },
  { .module = "errno",      .name = "get",                      .init = BUILTIN(builtin_errno_get)              },
  { .module = "errno",      .name = "str",                      .init = BUILTIN(builtin_errno_str)              },
  { .module = "time",       .name = "time",                     .init = BUILTIN(builtin_time_time)              },
  { .module = "time",       .name = "utime",                    .init = BUILTIN(builtin_time_utime)             },
  { .module = "time",       .name = "now",                      .init = BUILTIN(builtin_time_now)               },
  { .module = "time",       .name = "utc",                      .init = BUILTIN(builtin_time_utc)               },
  { .module = "time",       .name = "gettime",                  .init = BUILTIN(builtin_time_gettime)           },
  { .module = "time",       .name = "localtime",                .init = BUILTIN(builtin_time_localtime)         },
  { .module = "time",       .name = "zonetime",                 .init = BUILTIN(builtin_time_zonetime)          },
  { .module = "time",       .name = "gmtime",                   .init = BUILTIN(builtin_time_gmtime)            },
  { .module = "time",       .name = "strptime",                 .init = BUILTIN(builtin_time_strptime)          },
  { .module = "time",       .name = "strftime",                 .init = BUILTIN(builtin_time_strftime)          },
  { .module = "time",       .name = "CLOCK_REALTIME",           .init = INT(CLOCK_REALTIME)                     },
#ifdef CLOCK_REALTIME_COARSE
  { .module = "time",       .name = "CLOCK_REALTIME_COARSE",    .init = INT(CLOCK_REALTIME_COARSE)              },
#endif
  { .module = "time",       .name = "CLOCK_MONOTONIC",          .init = INT(CLOCK_MONOTONIC)                    },
#ifdef CLOCK_REALTIME_COARSE
  { .module = "time",       .name = "CLOCK_MONOTONIC_COARSE",   .init = INT(CLOCK_MONOTONIC_COARSE)             },
#endif
#ifdef CLOCK_PROCESS_CPUTIME_ID
  { .module = "time",       .name = "CLOCK_PROCESS_CPUTIME_ID", .init = INT(CLOCK_PROCESS_CPUTIME_ID)           },
#endif
#ifdef CLOCK_THREAD_CPUTIME_ID
  { .module = "time",       .name = "CLOCK_THREAD_CPUTIME_ID",  .init = INT(CLOCK_THREAD_CPUTIME_ID)            },
#endif
#ifdef CLOCK_MONOTONIC_RAW
  { .module = "time",       .name = "CLOCK_MONOTONIC_RAW",      .init = INT(CLOCK_MONOTONIC_RAW)                },
#endif
  { .module = "ptr",        .name = "null",                     .init = POINTER(NULL)                           },
  { .module = "ptr",        .name = "typed",                    .init = BUILTIN(builtin_ptr_typed)              },
  { .module = "ptr",        .name = "untyped",                  .init = BUILTIN(builtin_ptr_untyped)            },
  { .module = "ptr",        .name = "fromInt",                  .init = BUILTIN(builtin_ptr_from_int)           },

  { .module = "json",       .name = "parse",                    .init = BUILTIN(builtin_json_parse)             },
  { .module = "json",       .name = "parse!",                   .init = BUILTIN(builtin_json_parse_xD)          },
  { .module = "json",       .name = "encode",                   .init = BUILTIN(builtin_json_encode)            },
#ifdef SIGHUP
  { .module = "os",         .name = "SIGHUP",                   .init = INT(SIGHUP)                             },
#endif
#ifdef SIGINT
  { .module = "os",         .name = "SIGINT",                   .init = INT(SIGINT)                             },
#endif
#ifdef SIGQUIT
  { .module = "os",         .name = "SIGQUIT",                  .init = INT(SIGQUIT)                            },
#endif
#ifdef SIGILL
  { .module = "os",         .name = "SIGILL",                   .init = INT(SIGILL)                             },
#endif
#ifdef SIGTRAP
  { .module = "os",         .name = "SIGTRAP",                  .init = INT(SIGTRAP)                            },
#endif
#ifdef SIGABRT
  { .module = "os",         .name = "SIGABRT",                  .init = INT(SIGABRT)                            },
#endif
#ifdef SIGEMT
  { .module = "os",         .name = "SIGEMT",                   .init = INT(SIGEMT)                             },
#endif
#ifdef SIGFPE
  { .module = "os",         .name = "SIGFPE",                   .init = INT(SIGFPE)                             },
#endif
#ifdef SIGKILL
  { .module = "os",         .name = "SIGKILL",                  .init = INT(SIGKILL)                            },
#endif
#ifdef SIGBUS
  { .module = "os",         .name = "SIGBUS",                   .init = INT(SIGBUS)                             },
#endif
#ifdef SIGSEGV
  { .module = "os",         .name = "SIGSEGV",                  .init = INT(SIGSEGV)                            },
#endif
#ifdef SIGSYS
  { .module = "os",         .name = "SIGSYS",                   .init = INT(SIGSYS)                             },
#endif
#ifdef SIGPIPE
  { .module = "os",         .name = "SIGPIPE",                  .init = INT(SIGPIPE)                            },
#endif
#ifdef SIGALRM
  { .module = "os",         .name = "SIGALRM",                  .init = INT(SIGALRM)                            },
#endif
#ifdef SIGTERM
  { .module = "os",         .name = "SIGTERM",                  .init = INT(SIGTERM)                            },
#endif
#ifdef SIGURG
  { .module = "os",         .name = "SIGURG",                   .init = INT(SIGURG)                             },
#endif
#ifdef SIGSTOP
  { .module = "os",         .name = "SIGSTOP",                  .init = INT(SIGSTOP)                            },
#endif
#ifdef SIGTSTP
  { .module = "os",         .name = "SIGTSTP",                  .init = INT(SIGTSTP)                            },
#endif
#ifdef SIGCONT
  { .module = "os",         .name = "SIGCONT",                  .init = INT(SIGCONT)                            },
#endif
#ifdef SIGCHLD
  { .module = "os",         .name = "SIGCHLD",                  .init = INT(SIGCHLD)                            },
#endif
#ifdef SIGTTIN
  { .module = "os",         .name = "SIGTTIN",                  .init = INT(SIGTTIN)                            },
#endif
#ifdef SIGTTOU
  { .module = "os",         .name = "SIGTTOU",                  .init = INT(SIGTTOU)                            },
#endif
#ifdef SIGIO
  { .module = "os",         .name = "SIGIO",                    .init = INT(SIGIO)                              },
#endif
#ifdef SIGXCPU
  { .module = "os",         .name = "SIGXCPU",                  .init = INT(SIGXCPU)                            },
#endif
#ifdef SIGXFSZ
  { .module = "os",         .name = "SIGXFSZ",                  .init = INT(SIGXFSZ)                            },
#endif
#ifdef SIGVTALRM
  { .module = "os",         .name = "SIGVTALRM",                .init = INT(SIGVTALRM)                          },
#endif
#ifdef SIGPROF
  { .module = "os",         .name = "SIGPROF",                  .init = INT(SIGPROF)                            },
#endif
#ifdef SIGWINCH
  { .module = "os",         .name = "SIGWINCH",                 .init = INT(SIGWINCH)                           },
#endif
#ifdef SIGINFO
  { .module = "os",         .name = "SIGINFO",                  .init = INT(SIGINFO)                            },
#endif
#ifdef SIGUSR1
  { .module = "os",         .name = "SIGUSR1",                  .init = INT(SIGUSR1)                            },
#endif
#ifdef SIGUSR2
  { .module = "os",         .name = "SIGUSR2",                  .init = INT(SIGUSR2)                            },
#endif

  { .module = "os",         .name = "NSIG",                      .init = INT(32)                                },

  { .module = "os",         .name = "S_IFREG",                  .init = INT(S_IFREG)                            },
  { .module = "os",         .name = "S_IFDIR",                  .init = INT(S_IFDIR)                            },
#ifndef _WIN32
  { .module = "os",         .name = "S_IFMT",                   .init = INT(S_IFMT)                             },
  { .module = "os",         .name = "S_IFSOCK",                 .init = INT(S_IFSOCK)                           },
  { .module = "os",         .name = "S_IFLNK",                  .init = INT(S_IFLNK)                            },
  { .module = "os",         .name = "S_IFBLK",                  .init = INT(S_IFBLK)                            },
  { .module = "os",         .name = "S_IFCHR",                  .init = INT(S_IFCHR)                            },
  { .module = "os",         .name = "S_IFIFO",                  .init = INT(S_IFIFO)                            },
  { .module = "os",         .name = "S_ISUID",                  .init = INT(S_ISUID)                            },
  { .module = "os",         .name = "S_ISGID",                  .init = INT(S_ISGID)                            },
  { .module = "os",         .name = "S_ISVTX",                  .init = INT(S_ISVTX)                            },
  { .module = "os",         .name = "S_IRWXU",                  .init = INT(S_IRWXU)                            },
  { .module = "os",         .name = "S_IRUSR",                  .init = INT(S_IRUSR)                            },
  { .module = "os",         .name = "S_IWUSR",                  .init = INT(S_IWUSR)                            },
  { .module = "os",         .name = "S_IXUSR",                  .init = INT(S_IXUSR)                            },
  { .module = "os",         .name = "S_IRWXG",                  .init = INT(S_IRWXG)                            },
  { .module = "os",         .name = "S_IRGRP",                  .init = INT(S_IRGRP)                            },
  { .module = "os",         .name = "S_IWGRP",                  .init = INT(S_IWGRP)                            },
  { .module = "os",         .name = "S_IXGRP",                  .init = INT(S_IXGRP)                            },
  { .module = "os",         .name = "S_IRWXO",                  .init = INT(S_IRWXO)                            },
  { .module = "os",         .name = "S_IROTH",                  .init = INT(S_IROTH)                            },
  { .module = "os",         .name = "S_IWOTH",                  .init = INT(S_IWOTH)                            },
  { .module = "os",         .name = "S_IXOTH",                  .init = INT(S_IXOTH)                            },
  { .module = "os",         .name = "DT_BLK",                   .init = INT(DT_BLK)                             },
  { .module = "os",         .name = "DT_CHR",                   .init = INT(DT_CHR)                             },
  { .module = "os",         .name = "DT_DIR",                   .init = INT(DT_DIR)                             },
  { .module = "os",         .name = "DT_FIFO",                  .init = INT(DT_FIFO)                            },
  { .module = "os",         .name = "DT_SOCK",                  .init = INT(DT_SOCK)                            },
  { .module = "os",         .name = "DT_LNK",                   .init = INT(DT_LNK)                             },
  { .module = "os",         .name = "DT_REG",                   .init = INT(DT_REG)                             },
  { .module = "os",         .name = "DT_UNKNOWN",               .init = INT(DT_UNKNOWN)                         },
#endif

#ifndef _WIN32
  { .module = "termios",    .name = "CSIZE",                    .init = INT(CSIZE)                              },
  { .module = "termios",    .name = "CS5",                      .init = INT(CS5)                                },
  { .module = "termios",    .name = "CS6",                      .init = INT(CS6)                                },
  { .module = "termios",    .name = "CS7",                      .init = INT(CS7)                                },
  { .module = "termios",    .name = "CS8",                      .init = INT(CS8)                                },
  { .module = "termios",    .name = "CSTOPB",                   .init = INT(CSTOPB)                             },
  { .module = "termios",    .name = "CREAD",                    .init = INT(CREAD)                              },
  { .module = "termios",    .name = "PARENB",                   .init = INT(PARENB)                             },
  { .module = "termios",    .name = "PARODD",                   .init = INT(PARODD)                             },
  { .module = "termios",    .name = "HUPCL",                    .init = INT(HUPCL)                              },
  { .module = "termios",    .name = "CLOCAL",                   .init = INT(CLOCAL)                             },
  { .module = "termios",    .name = "IGNBRK",                   .init = INT(IGNBRK)                             },
  { .module = "termios",    .name = "BRKINT",                   .init = INT(BRKINT)                             },
  { .module = "termios",    .name = "IGNPAR",                   .init = INT(IGNPAR)                             },
  { .module = "termios",    .name = "PARMRK",                   .init = INT(PARMRK)                             },
  { .module = "termios",    .name = "INPCK",                    .init = INT(INPCK)                              },
  { .module = "termios",    .name = "ISTRIP",                   .init = INT(ISTRIP)                             },
  { .module = "termios",    .name = "INLCR",                    .init = INT(INLCR)                              },
  { .module = "termios",    .name = "IGNCR",                    .init = INT(IGNCR)                              },
  { .module = "termios",    .name = "ICRNL",                    .init = INT(ICRNL)                              },
  { .module = "termios",    .name = "IXON",                     .init = INT(IXON)                               },
  { .module = "termios",    .name = "IXANY",                    .init = INT(IXANY)                              },
  { .module = "termios",    .name = "IXOFF",                    .init = INT(IXOFF)                              },
  { .module = "termios",    .name = "IMAXBEL",                  .init = INT(IMAXBEL)                            },
  { .module = "termios",    .name = "IUTF8",                    .init = INT(IUTF8)                              },
  { .module = "termios",    .name = "OPOST",                    .init = INT(OPOST)                              },
  { .module = "termios",    .name = "ONLCR",                    .init = INT(ONLCR)                              },
  { .module = "termios",    .name = "OCRNL",                    .init = INT(OCRNL)                              },
  { .module = "termios",    .name = "ONOCR",                    .init = INT(ONOCR)                              },
  { .module = "termios",    .name = "ONLRET",                   .init = INT(ONLRET)                             },
#if defined(OFILL) && defined(OFDEL)
  { .module = "termios",    .name = "OFILL",                    .init = INT(OFILL)                              },
  { .module = "termios",    .name = "OFDEL",                    .init = INT(OFDEL)                              },
#endif
#if defined(VTDLY) && defined(VT0) && defined(VT1)
  { .module = "termios",    .name = "VTDLY",                    .init = INT(VTDLY)                              },
  { .module = "termios",    .name = "VT0",                      .init = INT(VT0)                                },
  { .module = "termios",    .name = "VT1",                      .init = INT(VT1)                                },
#endif
  { .module = "termios",    .name = "B0",                       .init = INT(B0)                                 },
  { .module = "termios",    .name = "B50",                      .init = INT(B50)                                },
  { .module = "termios",    .name = "B75",                      .init = INT(B75)                                },
  { .module = "termios",    .name = "B110",                     .init = INT(B110)                               },
  { .module = "termios",    .name = "B134",                     .init = INT(B134)                               },
  { .module = "termios",    .name = "B150",                     .init = INT(B150)                               },
  { .module = "termios",    .name = "B200",                     .init = INT(B200)                               },
  { .module = "termios",    .name = "B300",                     .init = INT(B300)                               },
  { .module = "termios",    .name = "B600",                     .init = INT(B600)                               },
  { .module = "termios",    .name = "B1200",                    .init = INT(B1200)                              },
  { .module = "termios",    .name = "B1800",                    .init = INT(B1800)                              },
  { .module = "termios",    .name = "B2400",                    .init = INT(B2400)                              },
  { .module = "termios",    .name = "B4800",                    .init = INT(B4800)                              },
  { .module = "termios",    .name = "B9600",                    .init = INT(B9600)                              },
  { .module = "termios",    .name = "B19200",                   .init = INT(B19200)                             },
  { .module = "termios",    .name = "B38400",                   .init = INT(B38400)                             },
  { .module = "termios",    .name = "TCOOFF",                   .init = INT(TCOOFF)                             },
  { .module = "termios",    .name = "TCOON",                    .init = INT(TCOON)                              },
  { .module = "termios",    .name = "TCIOFF",                   .init = INT(TCIOFF)                             },
  { .module = "termios",    .name = "TCION",                    .init = INT(TCION)                              },
  { .module = "termios",    .name = "TCIFLUSH",                 .init = INT(TCIFLUSH)                           },
  { .module = "termios",    .name = "TCOFLUSH",                 .init = INT(TCOFLUSH)                           },
  { .module = "termios",    .name = "TCIOFLUSH",                .init = INT(TCIOFLUSH)                          },
  { .module = "termios",    .name = "ISIG",                     .init = INT(ISIG)                               },
  { .module = "termios",    .name = "ICANON",                   .init = INT(ICANON)                             },
  { .module = "termios",    .name = "ECHO",                     .init = INT(ECHO)                               },
  { .module = "termios",    .name = "ECHOE",                    .init = INT(ECHOE)                              },
  { .module = "termios",    .name = "ECHOK",                    .init = INT(ECHOK)                              },
  { .module = "termios",    .name = "ECHONL",                   .init = INT(ECHONL)                             },
  { .module = "termios",    .name = "NOFLSH",                   .init = INT(NOFLSH)                             },
  { .module = "termios",    .name = "TOSTOP",                   .init = INT(TOSTOP)                             },
  { .module = "termios",    .name = "IEXTEN",                   .init = INT(IEXTEN)                             },
  { .module = "termios",    .name = "TCSANOW",                  .init = INT(TCSANOW)                            },
  { .module = "termios",    .name = "TCSADRAIN",                .init = INT(TCSADRAIN)                          },
  { .module = "termios",    .name = "TCSAFLUSH",                .init = INT(TCSAFLUSH)                          },
  { .module = "termios",    .name = "VMIN",                     .init = INT(VMIN)                               },
  { .module = "termios",    .name = "VTIME",                    .init = INT(VTIME)                              },
  { .module = "termios",    .name = "tcgetattr",                .init = BUILTIN(builtin_termios_tcgetattr)      },
  { .module = "termios",    .name = "tcsetattr",                .init = BUILTIN(builtin_termios_tcsetattr)      },
  { .module = "termios",    .name = "tcgetpgrp",                .init = BUILTIN(builtin_termios_tcgetpgrp)      },
  { .module = "termios",    .name = "tcsetpgrp",                .init = BUILTIN(builtin_termios_tcsetpgrp)      },
  { .module = "termios",    .name = "tcgetsid",                 .init = BUILTIN(builtin_termios_tcgetsid)       },
  { .module = "termios",    .name = "tcflush",                  .init = BUILTIN(builtin_termios_tcflush)        },
  { .module = "termios",    .name = "tcflow",                   .init = BUILTIN(builtin_termios_tcflow)         },
  { .module = "termios",    .name = "tcdrain",                  .init = BUILTIN(builtin_termios_tcdrain)        },
  { .module = "termios",    .name = "tcsendbreak",              .init = BUILTIN(builtin_termios_tcsendbreak)    },
#endif

  { .module = "ffi",        .name = "new",                      .init = BUILTIN(cffi_new)                       },
  { .module = "ffi",        .name = "box",                      .init = BUILTIN(cffi_box)                       },
  { .module = "ffi",        .name = "size",                     .init = BUILTIN(cffi_size)                      },
  { .module = "ffi",        .name = "alloc",                    .init = BUILTIN(cffi_alloc)                     },
  { .module = "ffi",        .name = "realloc",                  .init = BUILTIN(cffi_realloc)                   },
  { .module = "ffi",        .name = "free",                     .init = BUILTIN(cffi_free)                      },
  { .module = "ffi",        .name = "auto",                     .init = BUILTIN(cffi_auto)                      },
  { .module = "ffi",        .name = "newAuto",                  .init = BUILTIN(cffi_new_auto)                  },
  { .module = "ffi",        .name = "boxAuto",                  .init = BUILTIN(cffi_box_auto)                  },
  { .module = "ffi",        .name = "addr",                     .init = BUILTIN(cffi_addr)                      },
  { .module = "ffi",        .name = "load",                     .init = BUILTIN(cffi_load)                      },
  { .module = "ffi",        .name = "store",                    .init = BUILTIN(cffi_store)                     },
  { .module = "ffi",        .name = "call",                     .init = BUILTIN(cffi_call)                      },
  { .module = "ffi",        .name = "cif",                      .init = BUILTIN(cffi_cif)                       },
  { .module = "ffi",        .name = "fun",                      .init = BUILTIN(cffi_fun)                       },
  { .module = "ffi",        .name = "struct",                   .init = BUILTIN(cffi_struct)                    },
  { .module = "ffi",        .name = "closure",                  .init = BUILTIN(cffi_closure)                   },
  { .module = "ffi",        .name = "freeClosure",              .init = BUILTIN(cffi_closure_free)              },
  { .module = "ffi",        .name = "dlsym",                    .init = BUILTIN(cffi_dlsym)                     },
  { .module = "ffi",        .name = "dlopen",                   .init = BUILTIN(cffi_dlopen)                    },
  { .module = "ffi",        .name = "dlerror",                  .init = BUILTIN(cffi_dlerror)                   },
  { .module = "ffi",        .name = "member",                   .init = BUILTIN(cffi_member)                    },
  { .module = "ffi",        .name = "pmember",                  .init = BUILTIN(cffi_pmember)                   },
  { .module = "ffi",        .name = "fields",                   .init = BUILTIN(cffi_fields)                    },
  { .module = "ffi",        .name = "str",                      .init = BUILTIN(cffi_str)                       },
  { .module = "ffi",        .name = "blob",                     .init = BUILTIN(cffi_blob)                      },
  { .module = "ffi",        .name = "clone",                    .init = BUILTIN(cffi_clone)                     },
  { .module = "ffi",        .name = "as_str",                   .init = BUILTIN(cffi_as_str)                    },
  { .module = "ffi",        .name = "c_str",                    .init = BUILTIN(cffi_c_str)                     },
  { .module = "ffi",        .name = "calcsize",                 .init = BUILTIN(cffi_calcsize)                  },
  { .module = "ffi",        .name = "pack",                     .init = BUILTIN(cffi_pack)                      },
  { .module = "ffi",        .name = "unpack",                   .init = BUILTIN(cffi_unpack)                    },
  { .module = "atomic",     .name = "load",                     .init = BUILTIN(cffi_load_atomic)               },
  { .module = "atomic",     .name = "store",                    .init = BUILTIN(cffi_store_atomic)              },
  { .module = "ty",         .name = "gensym",                   .init = BUILTIN(builtin_ty_gensym)              },
  { .module = "ty",         .name = "eval",                     .init = BUILTIN(builtin_eval)                   },
  { .module = "ty",         .name = "scope",                    .init = BUILTIN(builtin_ty_scope)               },
  { .module = "ty",         .name = "ctx",                      .init = BUILTIN(builtin_ty_ctx)                 },
  { .module = "ty",         .name = "parse",                    .init = BUILTIN(builtin_ty_parse)               },
  { .module = "ty",         .name = "tokenize",                 .init = BUILTIN(builtin_ty_tokenize)            },
  { .module = "ty",         .name = "tokens",                   .init = BUILTIN(builtin_ty_tokens)              },
  { .module = "ty",         .name = "text",                     .init = BUILTIN(builtin_ty_text)                },
  { .module = "ty",         .name = "disassemble",              .init = BUILTIN(builtin_ty_disassemble)         },
  { .module = "ty",         .name = "copySource",               .init = BUILTIN(builtin_ty_copy_source)         },
  { .module = "ty",         .name = "stripSource",              .init = BUILTIN(builtin_ty_strip_source)        },
  { .module = "ty",         .name = "getSource",                .init = BUILTIN(builtin_ty_get_source)          },
  { .module = "ty",         .name = "id",                       .init = BUILTIN(builtin_ty_id)                  },
  { .module = "ty",         .name = "src",                      .init = BUILTIN(builtin_ty_get_source)          },
  { .module = "ty",         .name = "lock",                     .init = BUILTIN(builtin_ty_lock)                },
  { .module = "ty",         .name = "unlock",                   .init = BUILTIN(builtin_ty_unlock)              },
  { .module = "ty",         .name = "gc",                       .init = BUILTIN(builtin_ty_gc)                  },
  { .module = "ty",         .name = "bt",                       .init = BUILTIN(builtin_ty_bt)                  },
  { .module = "ty",         .name = "trace",                    .init = BUILTIN(builtin_ty_trace)               },
  { .module = "ty",         .name = "stack-ctx",                .init = BUILTIN(builtin_ty_stack_ctx)           },
  { .module = "ty",         .name = "valueSize",                .init = INT(sizeof (Value))                     },
  { .module = "ty",         .name = "definition",               .init = BUILTIN(builtin_ty_definition)          },
  { .module = "ty",         .name = "coro",                     .init = BUILTIN(builtin_ty_coro)                },

  { .module = "ty/mod",     .name = "get",                       .init = BUILTIN(builtin_ty_mod_get)            },
  { .module = "ty/mod",     .name = "load",                      .init = BUILTIN(builtin_ty_mod_load)           },
  { .module = "ty/mod",     .name = "list",                      .init = BUILTIN(builtin_ty_mod_list)           },
  { .module = "ty/mod",     .name = "name",                      .init = BUILTIN(builtin_ty_mod_name)           },
  { .module = "ty/mod",     .name = "ast",                       .init = BUILTIN(builtin_ty_mod_ast)            },
  { .module = "ty/mod",     .name = "source",                    .init = BUILTIN(builtin_ty_mod_source)         },
  { .module = "ty/mod",     .name = "tokens",                    .init = BUILTIN(builtin_ty_mod_tokens)         },
  { .module = "ty/mod",     .name = "path",                      .init = BUILTIN(builtin_ty_mod_path)           },
  { .module = "ty/mod",     .name = "dict",                      .init = BUILTIN(builtin_ty_mod_dict)           },
  { .module = "ty/mod",     .name = "imports",                   .init = BUILTIN(builtin_ty_mod_imports)        },
  { .module = "ty/mod",     .name = "lookup",                    .init = BUILTIN(builtin_ty_mod_lookup)         },

  { .module = "ty/types",   .name = "info",                     .init = BUILTIN(builtin_ty_type_info)           },
  { .module = "ty/types",   .name = "type",                     .init = BUILTIN(builtin_ty_type_type)           },
  { .module = "ty/types",   .name = "resolve",                  .init = BUILTIN(builtin_ty_type_resolve)        },
  { .module = "ty/types",   .name = "inst",                     .init = BUILTIN(builtin_ty_type_inst)           },
  { .module = "ty/types",   .name = "check",                    .init = BUILTIN(builtin_ty_type_check)          },
  { .module = "ty/types",   .name = "infer",                    .init = BUILTIN(builtin_ty_type_infer)          },
  { .module = "ty/types",   .name = "show",                     .init = BUILTIN(builtin_ty_type_show)           },

  { .module = "ty/token",   .name = "next",                     .init = BUILTIN(builtin_token_next)             },
  { .module = "ty/token",   .name = "peek",                     .init = BUILTIN(builtin_token_peek)             },

  { .module = "ty/parse",   .name = "source",                   .init = BUILTIN(builtin_parse_source)           },
  { .module = "ty/parse",   .name = "expr",                     .init = BUILTIN(builtin_parse_expr)             },
  { .module = "ty/parse",   .name = "type",                     .init = BUILTIN(builtin_parse_type)             },
  { .module = "ty/parse",   .name = "stmt",                     .init = BUILTIN(builtin_parse_stmt)             },
  { .module = "ty/parse",   .name = "fail",                     .init = BUILTIN(builtin_parse_fail)             },
  { .module = "ty/parse",   .name = "show",                     .init = BUILTIN(builtin_parse_show)             },
  { .module = "ty/parse",   .name = "highlight",                .init = BUILTIN(builtin_parse_highlight)        },
  { .module = "ty/parse",   .name = "raw",                      .init = BUILTIN(builtin_parse_raw)              },
  { .module = "ty/parse",   .name = "ast",                      .init = BUILTIN(builtin_parse_ast)              },

  { .module = "ty/lex",     .name = "peekc",                    .init = BUILTIN(builtin_lex_peek_char)          },
  { .module = "ty/lex",     .name = "getc",                     .init = BUILTIN(builtin_lex_next_char)          },
  { .module = "ty/lex",     .name = "state",                    .init = BUILTIN(builtin_lex_state)              },

  { .module = "tdb",        .name = "eval",                     .init = BUILTIN(builtin_tdb_eval)               },
  { .module = "tdb",        .name = "over",                     .init = BUILTIN(builtin_tdb_over)               },
  { .module = "tdb",        .name = "span",                     .init = BUILTIN(builtin_tdb_span)               },
  { .module = "tdb",        .name = "into",                     .init = BUILTIN(builtin_tdb_into)               },
  { .module = "tdb",        .name = "step",                     .init = BUILTIN(builtin_tdb_step)               },
  { .module = "tdb",        .name = "list",                     .init = BUILTIN(builtin_tdb_list)               },
  { .module = "tdb",        .name = "state",                    .init = BUILTIN(builtin_tdb_state)              },
  { .module = "tdb",        .name = "stack",                    .init = BUILTIN(builtin_tdb_stack)              },
  { .module = "tdb",        .name = "context",                  .init = BUILTIN(builtin_tdb_context)            },
  { .module = "tdb",        .name = "locals",                   .init = BUILTIN(builtin_tdb_locals)             },
  { .module = "tdb",        .name = "ip",                       .init = BUILTIN(builtin_tdb_ip)                 },
  { .module = "tdb",        .name = "insn",                     .init = BUILTIN(builtin_tdb_insn)               },
  { .module = "tdb",        .name = "breakpoint",               .init = BUILTIN(builtin_tdb_breakpoint)         },
  { .module = "tdb",        .name = "backtrace",                .init = BUILTIN(builtin_tdb_backtrace)          },

#ifndef _WIN32
  #include "ioctl_constants.h"
#endif

#include "errno_constants.h"

  { .module = "accelerate", .name = "vadd",          .init = BUILTIN(builtin_accel_vadd)            },
  { .module = "accelerate", .name = "vsub",          .init = BUILTIN(builtin_accel_vsub)            },
  { .module = "accelerate", .name = "vmul",          .init = BUILTIN(builtin_accel_vmul)            },
  { .module = "accelerate", .name = "vdiv",          .init = BUILTIN(builtin_accel_vdiv)            },
  { .module = "accelerate", .name = "vsadd",         .init = BUILTIN(builtin_accel_vsadd)           },
  { .module = "accelerate", .name = "vsmul",         .init = BUILTIN(builtin_accel_vsmul)           },
  { .module = "accelerate", .name = "vsdiv",         .init = BUILTIN(builtin_accel_vsdiv)           },
  { .module = "accelerate", .name = "svdiv",         .init = BUILTIN(builtin_accel_svdiv)           },
  { .module = "accelerate", .name = "vneg",          .init = BUILTIN(builtin_accel_vneg)            },
  { .module = "accelerate", .name = "vabs",          .init = BUILTIN(builtin_accel_vabs)            },
  { .module = "accelerate", .name = "vclip",         .init = BUILTIN(builtin_accel_vclip)           },
  { .module = "accelerate", .name = "vfill",         .init = BUILTIN(builtin_accel_vfill)           },
  { .module = "accelerate", .name = "vclr",          .init = BUILTIN(builtin_accel_vclr)            },
  { .module = "accelerate", .name = "vramp",         .init = BUILTIN(builtin_accel_vramp)           },
  { .module = "accelerate", .name = "vcopy",         .init = BUILTIN(builtin_accel_vcopy)           },
  { .module = "accelerate", .name = "vcast",         .init = BUILTIN(builtin_accel_vcast)           },
  { .module = "accelerate", .name = "vmath",         .init = BUILTIN(builtin_accel_vmath)           },
  { .module = "accelerate", .name = "vpow",          .init = BUILTIN(builtin_accel_vpow)            },
  { .module = "accelerate", .name = "vspow",         .init = BUILTIN(builtin_accel_vspow)           },
  { .module = "accelerate", .name = "vroundfn",      .init = BUILTIN(builtin_accel_vroundfn)        },
  { .module = "accelerate", .name = "sve",           .init = BUILTIN(builtin_accel_sve)             },
  { .module = "accelerate", .name = "maxv",          .init = BUILTIN(builtin_accel_maxv)            },
  { .module = "accelerate", .name = "minv",          .init = BUILTIN(builtin_accel_minv)            },
  { .module = "accelerate", .name = "countNz",       .init = BUILTIN(builtin_accel_count_nz)        },
  { .module = "accelerate", .name = "vcmpScalar",    .init = BUILTIN(builtin_accel_vcmp_scalar)     },
  { .module = "accelerate", .name = "vcmpArray",     .init = BUILTIN(builtin_accel_vcmp_array)      },
  { .module = "accelerate", .name = "boolIndex",     .init = BUILTIN(builtin_accel_bool_index)      },
  { .module = "accelerate", .name = "boolAssign",    .init = BUILTIN(builtin_accel_bool_assign)     },
  { .module = "accelerate", .name = "vcumsum",       .init = BUILTIN(builtin_accel_vcumsum)         },
  { .module = "accelerate", .name = "vrandn",        .init = BUILTIN(builtin_accel_vrandn)          },
  { .module = "accelerate", .name = "vrand",         .init = BUILTIN(builtin_accel_vrand)           },
  { .module = "accelerate", .name = "mtrans",        .init = BUILTIN(builtin_accel_mtrans)          },
  { .module = "accelerate", .name = "transposeNd",   .init = BUILTIN(builtin_accel_transpose_nd)    },
  { .module = "accelerate", .name = "broadcastBinop",.init = BUILTIN(builtin_accel_broadcast_binop) },
  { .module = "accelerate", .name = "sumAxis0",      .init = BUILTIN(builtin_accel_sum_axis0)       },
  { .module = "accelerate", .name = "vget",          .init = BUILTIN(builtin_accel_vget)            },
  { .module = "accelerate", .name = "vset",          .init = BUILTIN(builtin_accel_vset)            },
  { .module = "accelerate", .name = "fromList",      .init = BUILTIN(builtin_accel_from_list)       },
  { .module = "accelerate", .name = "fromList2d",    .init = BUILTIN(builtin_accel_from_list2d)     },
  { .module = "accelerate", .name = "toList",        .init = BUILTIN(builtin_accel_to_list)         },
  { .module = "accelerate", .name = "vselect",       .init = BUILTIN(builtin_accel_vselect)         },
  { .module = "accelerate", .name = "oneHot",        .init = BUILTIN(builtin_accel_one_hot)         },
  { .module = "accelerate", .name = "argmaxAxis1",   .init = BUILTIN(builtin_accel_argmax_axis1)    },
  { .module = "accelerate", .name = "vtrace",        .init = BUILTIN(builtin_accel_vtrace)          },
  { .module = "accelerate", .name = "arrayEq",       .init = BUILTIN(builtin_accel_array_eq)        },
  { .module = "accelerate", .name = "vmulMask",      .init = BUILTIN(builtin_accel_vmul_mask)       },
  { .module = "accelerate", .name = "addRow",        .init = BUILTIN(builtin_accel_add_row)         },
  { .module = "accelerate", .name = "accuracy",      .init = BUILTIN(builtin_accel_accuracy)        },
  { .module = "accelerate", .name = "fromBytes",     .init = BUILTIN(builtin_accel_from_bytes)      },
  { .module = "accelerate", .name = "softmax",       .init = BUILTIN(builtin_accel_softmax)         },
  { .module = "accelerate", .name = "crossEntropy",  .init = BUILTIN(builtin_accel_cross_entropy)   },
  { .module = "accelerate", .name = "causalSoftmax", .init = BUILTIN(builtin_accel_causal_softmax)  },
  { .module = "accelerate", .name = "promote",       .init = BUILTIN(builtin_accel_promote)         },
  { .module = "accelerate", .name = "hstack2d",      .init = BUILTIN(builtin_accel_hstack_2d)       },
  { .module = "accelerate", .name = "fromRaw",       .init = BUILTIN(builtin_accel_from_raw)        },
  { .module = "accelerate", .name = "sliceCols",     .init = BUILTIN(builtin_accel_slice_cols)      },
  { .module = "accelerate", .name = "mhaForward",    .init = BUILTIN(builtin_accel_mha_forward)     },
  { .module = "accelerate", .name = "mhaForwardOne", .init = BUILTIN(builtin_accel_mha_forward_one) },
  { .module = "accelerate", .name = "mhaBackward",   .init = BUILTIN(builtin_accel_mha_backward)    },
  { .module = "accelerate", .name = "kvCacheAlloc",  .init = BUILTIN(builtin_accel_kv_cache_alloc)  },
  { .module = "accelerate", .name = "causalSoftmaxBackward", .init = BUILTIN(builtin_accel_causal_softmax_backward) },

};
